image: node:18

.shared: &shared
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
    - release/*

.npm-job: &npm-job
  <<: *shared
  before_script:
    - export NODE_OPTIONS="--max-old-space-size=8192"
    - npm ci --cache .npm --prefer-offline

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - check
  - build

prettier:
  stage: check
  <<: *npm-job
  script:
    - npm run check

eslint:
  stage: check
  <<: *npm-job
  script:
    - node_modules/eslint/bin/eslint.js web/

build-nuxt:
  stage: build
  <<: *npm-job
  script:
    - cd web
    - npm run build

build-web-main:
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind
  stage: build
  only:
    - main
  script:
    - docker build -f web.Dockerfile -t "todo_system_web:$CI_COMMIT_SHORT_SHA" -t "todo_system_web:$CI_COMMIT_BRANCH" -t "todo_system_web:$CI_COMMIT_TAG" -t "todo_system_web:latest"
#    - docker push "todo_system_web:latest"

build-web:
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind
  stage: build
  only:
    - release/*
    - tags
  script:
    - docker build -f web.Dockerfile -t "todo_system_web:$CI_COMMIT_SHORT_SHA" -t "todo_system_web:$CI_COMMIT_BRANCH" -t "todo_system_web:$CI_COMMIT_TAG"
#    - docker push "todo_system_web:$CI_COMMIT_SHORT_SHA"
