image: node:18

.shared: &shared
  tags:
    - docker
  only:
    - main
    - merge_requests
    - tags
    - release/*

.npm-job: &npm-job
  <<: *shared
  before_script:
    - export NODE_OPTIONS="--max-old-space-size=8192"
    - npm ci --cache .npm --prefer-offline

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

stages:
  - check
  - build

prettier:
  stage: check
  <<: *npm-job
  script:
    - npm run check

eslint:
  stage: check
  <<: *npm-job
  script:
    - node_modules/eslint/bin/eslint.js web/

build-nuxt:
  stage: build
  <<: *npm-job
  script:
    - cd web
    - npm run build
